apiVersion: v1
kind: Pod
metadata:
  name: volume-share-datacenter
spec:
  containers:
  - name: volume-container-datacenter-1
    image: ubuntu:latest
    command: ["sleep", "infinity"]
    volumeMounts:
    - mountPath: /tmp/official
      name: volume-share

  - name: volume-container-datacenter-2
    image: ubuntu:latest
    command: ["sleep", "infinity"]
    volumeMounts:
    - mountPath: /tmp/cluster
      name: volume-share
  volumes:
  - name: volume-share
    emptyDir: {}
