apiVersion: v1
data:
  maxmemory: 2mb
  maxmemory-policy: allkeys-lru
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"maxmemory":"2mb","maxmemory-policy":"allkeys-lru"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"redis-config","namespace":"default"}}
  creationTimestamp: "2025-10-21T11:37:29Z"
  name: redis-config
  namespace: default
  resourceVersion: "665"
  uid: 2c1640a5-2574-4adb-a3c8-ad795026dc38
